dashpay/wp-dash-theme

assets/dash.css, functions.php
Hi Leon! Now that I got access to my email I was able to finish my Github account setup. I copied/pasted some of the code that I wrote. Not done with this yet, but would love to test and see if it works like I'm hoping it will without my styles being overwritten. I was careful to use the page-id-class so my styles shouldn't interfere with other pages. 
Is there a way for me to get access to the stylesheet so that I can make changes to it without having to wait for approval? It's hard to know if my code will work when I can't preview it as I work. I was unable to get the WordPress custom code thing to work (when I tried to publish, it said I didn't have access).
=> feat: add CSS to support testing

assets/dash.css
Adjusted banner height and type styling.
Please let me know if you see anything that needs to be done differently. :)
=> fix: More eSports CSS tweaks

assets/dash.css
Also, some eSports style tweaks and some Where To Spend style tweaks for the new DashDirect section... and made the footer a little darker. Will anyone notice...? ;)
=> fix: style changes to blog page/posts

single.php
Moved the "Back to all articles" button to the bottom of page
=> fix: layout tweak

assets/dash.css, functions.php
From my brand-spankin' new repository.
=> fix: CSS updates for eSports

assets/dash.css, page-lg.php
Will add the content on wp.dash.org once the css is updated on the server. :)
=> feat: dashdirect feature and button on homepage

assets/dash.css
=> fix: tweaking image dimensions on blog

assets/dash.css, footer.php, functions.php, page-lg.php
I made sure my fork was up to date with dashevo, created a new branch, and still for some weird reason it's showing a whole bunch of commits with this pull request. But it's only showing the three files that I changed for the footer. Are you able to merge the updated files? (footer.php, dash.css, and functions.php)
=> feat: move social media up in footer

assets/dash.css, functions.php
I deleted my fork and recreated it and it seems to be fixed now!  🥳
=> feat: connect with us page

assets/dash.css, functions.php
=> feat: Valkyrie Landing Page

inc/content_lg.php
Let me know if anything needs to be tweaked. Still learning over here. :D
=> feat: Content_lg.php template updates

assets/dash.css, functions.php, inc/content_lg.php
This was such a huge page! And I uncovered a few theme issues that need to be addressed but I wanted to discuss with you Leon before attempting to fix them on all pages. Maybe we can chat sometime soon! :)
=> feat: Merchant kit landing page

assets/dash.css, functions.php
I used the page-id class in style because this CSS class doesn't change and it locked under each page just to specify it. I will need to add more options for ACF on this point or to change a structure for a bit.
=> feat:responsive-tables-faq

assets/dash.css
I used the page-id class in style because this CSS class doesn't change and it locked under each page just to specify it. I will need to add more options for ACF on this point or to change a structure for a bit.
=> fix:docs-page-style

page-brandasset.php, page-brandguidelines.php, page-buyspend.php, page-communityarticle.php, page-contact.php, page-downloads.php, page-faq.php, page-legal.php, page-lg.php, page-roadmap.php, page-team.php
Solution for main sections id instead of body class - this works for all languages, tested in staging server
=> chore: id-for-main-sections

assets/dash.css, functions.php
I've already set a needed IDs for each page I removed page-id-*number*, should be no problem in styling after merging
=> fix:removing-page-ids-from-css

assets/dash.js, functions.php
I've noticed that the function sign is missing, so I fixed it 🤡  
also I commented previous Sendgrid code, to avoid this red notification in the issue list, Daniel re-worked it anyway
=> fix:js-issue-fixing

assets/dash.css, functions.php, single.php
Fix for title hierarchy, made blog posts a bit wider for easy reading, and fix the different heights of posts grid
=> fix: blog post formatting 

assets/dash.css, functions.php, inc/halfbanner.php
New feature graphic currencies
=> feat:new-graphic

assets/dash.css, assets/dash.js, functions.php
Reopened: https://github.com/dashpay/wp-dash-theme/pull/170
See prior PR for discussion
=> Small style fix

assets/dash.js, functions.php
Remove JS code for timer since we don't need anymore, and will re-work if will need in future
=> fix:header-expire-fix

assets/dash.css, assets/dash.js, assets/home.css, functions.php, header.php, inc/content_lg.php
The brand new design for the home page
Changes:
- New menu
- Fully new page
- New font and sizes
- New CSS file
- New ACF fields 
Also, I have beautified the CSS files and applied functions where home.css works only for the Home Page
=> feat:new-home-page-design

assets/home.css, inc/halfbanner.php
Fix:
White font for nav download page
Slider not showing in Arabic and Persian 
Change:
Mobile button home page
=> fix:download-page

assets/dash.js, functions.php
Simply removed animation from JS, it's and old way for simple animations
=> fix:animation-remove

footer.php
Adding one more link to the bottom of footer
=> feat:small-change-footer
